export interface Item {
  id?: number;
  // id is optional in cases where we add an item, the user doesn't supply id directly (it is autogenerated) but we do retreive the item with the id from the db
  name: string;
  type: string;
  price: number;
  quantity: number;
}

export interface Sale {
  id: number;
  item: Item;
}
